### ISSUE TITLE
PA3

### ISSUE THREAD

**Issue by vkuzn** [loolllka/RP#1]
Вытяните репозиторий в новую папку и попробуйте запустить скрипт start.cmd
Приложение не запустится. Исправьте и проверьте чтобы всё работало.

**Comment by loolllka** [comment]
Извините, не все файлы нужные загрузила. Исправила

**Comment by vkuzn** [comment]
https://github.com/loolllka/RP/blob/bc6d40b7552e478c6dcb98aa8c6b9671eee36879/Valuator/Pages/About.cshtml#L8
